### ISSUE TITLE
unable to deserialize or serialize container like this

### ISSUE THREAD

**Issue by scopor** [PantheonTechnologies/lighty-core#369]
closed: unable to reproduce

_Originally posted by @mmiklus in https://github.com/PantheonTechnologies/lighty-core/issues/328#issuecomment-553882119_

I used lighty-core/lighty-codec to serialize and deserialize container like :

container food {
 container rice {
 }
}

or 

container teacher {
 list course {
 
 }
}

but there is an exception. I don't know whether the code I set is wrong or whether the Yang structure containing list in the container is not supported. Can anyone help me ?

Caused by: java.lang.RuntimeException: cannot find org.opendaylight.yang.gen.v1.urn.ietf.params.xml.ns.yang.ietf.interfaces.rev140508.interfaces: org.opendaylight.yang.gen.v1.urn.ietf.params.xml.ns.yang.ietf.interfaces.rev140508.Interfaces found in org/opendaylight/yang/gen/v1/urn/ietf/params/xml/ns/yang/ietf/interfaces/rev140508/interfaces.class
	at javassist.CtClassType.getClassFile3(CtClassType.java:213) ~[javassist-3.26.0-GA.jar:na]
	at javassist.CtClassType.makeFieldCache(CtClassType.java:970) ~[javassist-3.26.0-GA.jar:na]
	at javassist.CtClassType.getMembers(CtClassType.java:961) ~[javassist-3.26.0-GA.jar:na]
	at javassist.CtClassType.getDeclaredField2(CtClassType.java:1086) ~[javassist-3.26.0-GA.jar:na]
	at javassist.CtClassType.getField2(CtClassType.java:1038) ~[javassist-3.26.0-GA.jar:na]
	at javassist.CtClassType.getField(CtClassType.java:1019) ~[javassist-3.26.0-GA.jar:na]
	at javassist.CtClass.getField(CtClass.java:846) ~[javassist-3.26.0-GA.jar:na]
	at javassist.compiler.MemberResolver.lookupFieldByJvmName2(MemberResolver.java:292) ~[javassist-3.26.0-GA.jar:na]
	at javassist.compiler.TypeChecker.fieldAccess2(TypeChecker.java:941) ~[javassist-3.26.0-GA.jar:na]
	at javassist.compiler.TypeChecker.fieldAccess(TypeChecker.java:898) ~[javassist-3.26.0-GA.jar:na]
	at javassist.compiler.TypeChecker.atFieldRead(TypeChecker.java:831) ~[javassist-3.26.0-GA.jar:na]
	at javassist.compiler.TypeChecker.atExpr(TypeChecker.java:605) ~[javassist-3.26.0-GA.jar:na]
	at javassist.compiler.ast.Expr.accept(Expr.java:71) ~[javassist-3.26.0-GA.jar:na]
	at javassist.compiler.TypeChecker.atCallExpr(TypeChecker.java:693) ~[javassist-3.26.0-GA.jar:na]
	at javassist.compiler.JvstTypeChecker.atCallExpr(JvstTypeChecker.java:170) ~[javassist-3.26.0-GA.jar:na]
	at javassist.compiler.ast.CallExpr.accept(CallExpr.java:49) ~[javassist-3.26.0-GA.jar:na]
	at javassist.compiler.TypeChecker.atCallExpr(TypeChecker.java:693) ~[javassist-3.26.0-GA.jar:na]
	at javassist.compiler.JvstTypeChecker.atCallExpr(JvstTypeChecker.java:170) ~[javassist-3.26.0-GA.jar:na]
	at javassist.compiler.ast.CallExpr.accept(CallExpr.java:49) ~[javassist-3.26.0-GA.jar:na]
	at javassist.compiler.CodeGen.doTypeCheck(CodeGen.java:266) ~[javassist-3.26.0-GA.jar:na]
	at javassist.compiler.CodeGen.atStmnt(CodeGen.java:360) ~[javassist-3.26.0-GA.jar:na]
	at javassist.compiler.ast.Stmnt.accept(Stmnt.java:53) ~[javassist-3.26.0-GA.jar:na]
	at javassist.compiler.CodeGen.atStmnt(CodeGen.java:381) ~[javassist-3.26.0-GA.jar:na]
	at javassist.compiler.ast.Stmnt.accept(Stmnt.java:53) ~[javassist-3.26.0-GA.jar:na]
	at javassist.compiler.CodeGen.atIfStmnt(CodeGen.java:428) ~[javassist-3.26.0-GA.jar:na]
	at javassist.compiler.CodeGen.atStmnt(CodeGen.java:385) ~[javassist-3.26.0-GA.jar:na]
	at javassist.compiler.ast.Stmnt.accept(Stmnt.java:53) ~[javassist-3.26.0-GA.jar:na]
	at javassist.compiler.CodeGen.atStmnt(CodeGen.java:381) ~[javassist-3.26.0-GA.jar:na]
	at javassist.compiler.ast.Stmnt.accept(Stmnt.java:53) ~[javassist-3.26.0-GA.jar:na]
	at javassist.compiler.CodeGen.atWhileStmnt(CodeGen.java:467) ~[javassist-3.26.0-GA.jar:na]
	at javassist.compiler.CodeGen.atStmnt(CodeGen.java:387) ~[javassist-3.26.0-GA.jar:na]
	at javassist.compiler.ast.Stmnt.accept(Stmnt.java:53) ~[javassist-3.26.0-GA.jar:na]
	at javassist.compiler.CodeGen.atStmnt(CodeGen.java:381) ~[javassist-3.26.0-GA.jar:na]
	at javassist.compiler.ast.Stmnt.accept(Stmnt.java:53) ~[javassist-3.26.0-GA.jar:na]
	at javassist.compiler.CodeGen.atIfStmnt(CodeGen.java:428) ~[javassist-3.26.0-GA.jar:na]
	at javassist.compiler.CodeGen.atStmnt(CodeGen.java:385) ~[javassist-3.26.0-GA.jar:na]
	at javassist.compiler.ast.Stmnt.accept(Stmnt.java:53) ~[javassist-3.26.0-GA.jar:na]
	at javassist.compiler.CodeGen.atStmnt(CodeGen.java:381) ~[javassist-3.26.0-GA.jar:na]
	at javassist.compiler.ast.Stmnt.accept(Stmnt.java:53) ~[javassist-3.26.0-GA.jar:na]
	at javassist.compiler.CodeGen.atMethodBody(CodeGen.java:321) ~[javassist-3.26.0-GA.jar:na]
	at javassist.compiler.Javac.compileBody(Javac.java:228) ~[javassist-3.26.0-GA.jar:na]
	at javassist.CtBehavior.setBody(CtBehavior.java:466) ~[javassist-3.26.0-GA.jar:na]
	at javassist.CtBehavior.setBody(CtBehavior.java:440) ~[javassist-3.26.0-GA.jar:na]

**Comment by scopor** [comment]
java version 1.8.0_212
lighty-core 11.0.x

**Comment by scopor** [comment]
close: AppClassLoader not case sensitive in windows
